sudo: true
node_js: "7"

cache:
  directories:
    - node_modules

env:
  global:
  - SFDX_AUTOUPDATE_DISABLE=true
  - SFDX_DOMAIN_RETRY=300
  - SFDX_USE_GENERIC_UNIX_KEYCHAIN=true

before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- wget -qO- https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz | tar -xvJf -
- ./sfdx/install
- echo force://$CLIENT_ID:$CLIENT_SECRET:$REFRESH_TOKEN@$INSTANCE_URL > .sfdx-url
- sfdx force:auth:sfdxurl:store -s -f ./.sfdx-url -a DefaultOrg
- npm install apexcov -g

script:
- sfdx force:org:create -s -f scratchdef.json -a ci
- sfdx force:source:push -u ci
- mkdir coverage
- sfdx force:apex:test:run -r json -u ci -c > coverage/coverage.json
- cat coverage/coverage.json
- apexcov
- sfdx force:org:delete -u ci -p
- ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT