env:
- GOPATH=$HOME/go PATH=$GOPATH/bin:$PATH
before_script:
- npm install -g coveralls codeclimate-test-reporter
- go get github.com/jpmonette/apexcov
script:
- apexcov --username="${CI_USERNAME}" --password="${CI_PASSWORD}"
- "cat ./coverage/lcov.info | coveralls"
- codeclimate-test-reporter < ./coverage/lcov.info