env:
- GOPATH=$HOME/go PATH=$GOPATH/bin:$PATH
before_script:
- npm install -g coveralls
- npm install -g codeclimate-test-reporter
- go get github.com/jpmonette/apexcov
script:
- apexcov
- cat ./coverage/lcov.info | coveralls
- codeclimate-test-reporter < ./coverage/lcov.info
